// GET /api/scan/corpus
//
// How much work Helm did that nobody saw.
//
// The product sells its contradictions — the ~72 findings a month where a
// document argues against a reason people hold something. It shows none of the
// ~1,150 documents it read to find them. That is backwards for a product whose
// whole claim is that it reads the filings: the catches are the output, the
// reading is the proof of work, and the reading is a much larger number.
//
// It also fixes a promise problem. A single tracked thesis produces an adverse
// finding roughly once every seven weeks, so "I will tell you when this stops
// being true" is followed by two months of silence. A corpus figure reframes
// that silence honestly: nothing broke, and here is how much was checked to
// know that.
//
// PUBLIC and AGGREGATE ONLY. pillar_evidence carries user_id and rows generated
// by private user theses, so nothing here returns a ticker list, a pillar, a
// claim, or any per-user shape — only counts. A count of documents read is a
// property of the corpus, not of anybody's book.

import { NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase/server';
import { HOUSE_THESES } from '@/lib/content/house-theses';

export const dynamic = 'force-dynamic';

const WINDOW_DAYS = 30;

interface PublishedRow {
  ticker: string; company: string | null; verdict: string;
  verbatim_cite: string; cite_date: string | null; run_date: string | null;
  source_type: string | null;
}

export interface CorpusStats {
  windowDays: number;
  /** THE HEADLINE UNIT. Reasons under active watch — the thing nobody else
   *  tracks. Everyone reads the news; only this counts specific claims and says
   *  when one stops holding. It also cannot be inflated by junk sources. */
  reasons: number;
  /** Distinct tickers carrying a tracked thesis. */
  companies: number;
  /** Distinct sources read. "Sources", never "documents": 94% of these are news
   *  articles, and next to a product that says it reads the filings, the word
   *  "documents" implies 1,154 filings when 72 of them are. */
  sources: number;
  /** Of those sources, the ones that are actual company filings. Small, and
   *  stated separately rather than hidden inside the total. */
  filings: number;
  /** Every finding filed against a reason in the window. */
  findings: number;
  /** Findings the judge rated `material` rather than `context`. The
   *  conservative figure, for any surface that would rather understate. */
  material: number;
  /** Findings that argued AGAINST a reason someone holds something. */
  contradictions: number;
  /** DISTINCT reasons that took a contradiction. Always <= contradictions,
   *  because one reason can be hit several times in a month — 72 findings
   *  landed on 44 reasons. Any copy of the form "N of them stopped holding up"
   *  has to use THIS, or it counts the same broken reason repeatedly. */
  reasonsContradicted: number;
  /** Most recent day anything was filed, so a stale corpus cannot pose as live. */
  lastFiledISO: string | null;
  /** A handful of REAL published calls, for a surface that wants to show the
   *  work rather than assert it. Drawn from content_events joined to APPROVED
   *  content_queue rows — the same vetted record /thesis/[ticker] renders, not
   *  raw pillar_evidence, which carries rows generated by private user theses. */
  recent: {
    ticker: string;
    company: string | null;
    verdict: string;
    verbatimCite: string;
    dateISO: string;
    sourceLabel: string;
  }[];
  /** The PUBLIC house universe — the same names already published at
   *  /thesis/<ticker>. Safe to render anywhere, and unlike the set of tickers
   *  users actually track it says nothing about anyone's book. For a surface
   *  that wants to show breadth rather than assert it. */
  universe: string[];
}

/** 'filing' and 'minor_news' are the stored values; neither is a sentence. */
function sourceLabel(t: string | null): string {
  const s = String(t ?? '');
  if (s === 'filing') return 'SEC filing';
  if (s.includes('news')) return 'News';
  return 'Source';
}

export async function GET() {
  try {
    const supabase = await createServiceClient();
    const since = new Date(Date.now() - WINDOW_DAYS * 86400000).toISOString();

    // PostgREST caps a select at 1000 rows and returns no error when it
    // truncates, so an unpaged read would silently report a fraction of the
    // corpus as the whole of it — understating the one number this route
    // exists to state.
    const rows: {
      verdict: string | null; source_url: string | null; source_type: string | null;
      materiality: string | null; pillar_id: string | null; created_at: string;
    }[] = [];
    for (let from = 0; ; from += 1000) {
      const { data, error } = await supabase
        .from('pillar_evidence')
        .select('verdict, source_url, source_type, materiality, pillar_id, created_at')
        .gte('created_at', since)
        .range(from, from + 999);
      if (error) throw error;
      rows.push(...(data ?? []));
      if (!data || data.length < 1000) break;
    }

    const sources = new Set(rows.map((r) => r.source_url).filter(Boolean)).size;
    const filings = new Set(
      rows.filter((r) => r.source_type === 'filing').map((r) => r.source_url).filter(Boolean),
    ).size;
    const reasons = new Set(rows.map((r) => r.pillar_id).filter(Boolean)).size;
    const contradictions = rows.filter((r) => /contradict/i.test(r.verdict ?? '')).length;
    const material = rows.filter((r) => r.materiality === 'material').length;
    const reasonsContradicted = new Set(
      rows.filter((r) => /contradict/i.test(r.verdict ?? '')).map((r) => r.pillar_id).filter(Boolean),
    ).size;

    // Companies under watch, not sources read. Counted from tracked theses
    // rather than from evidence, so a quiet week does not shrink the number of
    // things Helm is watching — which would be false.
    const { data: tracked } = await supabase.from('theses').select('ticker').eq('tracked', true);
    const companies = new Set((tracked ?? []).map((t) => String(t.ticker).toUpperCase())).size;
    const lastFiledISO = rows.length
      ? rows.reduce((m, r) => (r.created_at > m ? r.created_at : m), rows[0].created_at).slice(0, 10)
      : null;

    // The published record. Newest first, contradictions preferred: an intro
    // that leads with "supports" is showing Helm agreeing with the consensus,
    // which is the least interesting thing it does.
    const { data: pub } = await supabase
      .from('content_queue')
      .select('status, content_events!inner(ticker, company, verdict, verbatim_cite, cite_date, run_date, source_type)')
      .eq('status', 'approved');
    const seen = new Set<string>();
    const seenTicker = new Set<string>();
    const recent = ((pub ?? []) as unknown as { content_events: PublishedRow | null }[])
      .map((r) => r.content_events)
      .filter((e): e is PublishedRow => !!e && !!e.verbatim_cite)
      // ONE ENTRY PER TICKER, and one per quote.
      //
      // A list whose job is to prove range reads as the opposite when the same
      // company appears twice, and the published record currently contains 8
      // pairs where one filing was published twice under different sentences
      // (fixed forward in the content cron; the existing rows remain). Keying
      // on the ticker means such a pair can never both surface here, so a data
      // problem in the archive cannot become a credibility problem on the first
      // screen anyone sees.
      .filter((e) => {
        const k = e.verbatim_cite.replace(/\s+/g, ' ').trim().toLowerCase();
        const t = e.ticker.toUpperCase();
        if (seen.has(k) || seenTicker.has(t)) return false;
        seen.add(k);
        seenTicker.add(t);
        return true;
      })
      .sort((a, b) => {
        const av = /contradict/i.test(a.verdict) ? 0 : 1;
        const bv = /contradict/i.test(b.verdict) ? 0 : 1;
        if (av !== bv) return av - bv;
        return String(b.cite_date ?? b.run_date).localeCompare(String(a.cite_date ?? a.run_date));
      })
      .slice(0, 6)
      .map((e) => ({
        ticker: e.ticker,
        company: e.company ?? null,
        verdict: e.verdict,
        verbatimCite: e.verbatim_cite,
        dateISO: String(e.cite_date ?? e.run_date ?? '').slice(0, 10),
        sourceLabel: sourceLabel(e.source_type),
      }));

    const stats: CorpusStats = {
      windowDays: WINDOW_DAYS,
      reasons,
      companies,
      sources,
      filings,
      findings: rows.length,
      material,
      contradictions,
      reasonsContradicted,
      lastFiledISO,
      recent,
      universe: HOUSE_THESES.map((t) => t.ticker),
    };

    return NextResponse.json(stats, {
      // Changes once a day at most, and every consumer is a marketing surface
      // rather than a decision surface. Long cache, longer stale window.
      headers: { 'Cache-Control': 'public, max-age=1800, stale-while-revalidate=86400' },
    });
  } catch (error) {
    console.error('corpus stats failed:', error instanceof Error ? error.message : 'unknown');
    // A marketing statistic must never be able to break a page that is trying
    // to render. Callers treat null as "say nothing" rather than "say zero" —
    // claiming Helm read zero documents is worse than claiming nothing.
    return NextResponse.json({ error: 'unavailable' }, { status: 503 });
  }
}
