// GET /api/scan/corpus
//
// How much work Helm did that nobody saw.
//
// The product sells its contradictions — the ~72 findings a month where a
// document argues against a reason people hold something. It shows none of the
// ~1,150 documents it read to find them. That is backwards for a product whose
// whole claim is that it reads the filings: the catches are the output, the
// reading is the proof of work, and the reading is a much larger number.
//
// It also fixes a promise problem. A single tracked thesis produces an adverse
// finding roughly once every seven weeks, so "I will tell you when this stops
// being true" is followed by two months of silence. A corpus figure reframes
// that silence honestly: nothing broke, and here is how much was checked to
// know that.
//
// PUBLIC and AGGREGATE ONLY. pillar_evidence carries user_id and rows generated
// by private user theses, so nothing here returns a ticker list, a pillar, a
// claim, or any per-user shape — only counts. A count of documents read is a
// property of the corpus, not of anybody's book.

import { NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase/server';

export const dynamic = 'force-dynamic';

const WINDOW_DAYS = 30;

interface PublishedRow {
  ticker: string; company: string | null; verdict: string;
  verbatim_cite: string; cite_date: string | null; run_date: string | null;
  source_type: string | null;
}

export interface CorpusStats {
  windowDays: number;
  /** Distinct source documents read. The headline: the work, not the output. */
  documents: number;
  /** Every piece of evidence filed against a pillar in the window. */
  evidence: number;
  /** Evidence that argued AGAINST a reason someone holds something. */
  contradictions: number;
  /** Reasons under active watch, across every tracked thesis. */
  pillars: number;
  /** Most recent day anything was filed, so a stale corpus cannot pose as live. */
  lastFiledISO: string | null;
  /** A handful of REAL published calls, for a surface that wants to show the
   *  work rather than assert it. Drawn from content_events joined to APPROVED
   *  content_queue rows — the same vetted record /thesis/[ticker] renders, not
   *  raw pillar_evidence, which carries rows generated by private user theses. */
  recent: {
    ticker: string;
    company: string | null;
    verdict: string;
    verbatimCite: string;
    dateISO: string;
    sourceLabel: string;
  }[];
}

/** 'filing' and 'minor_news' are the stored values; neither is a sentence. */
function sourceLabel(t: string | null): string {
  const s = String(t ?? '');
  if (s === 'filing') return 'SEC filing';
  if (s.includes('news')) return 'News';
  return 'Source';
}

export async function GET() {
  try {
    const supabase = await createServiceClient();
    const since = new Date(Date.now() - WINDOW_DAYS * 86400000).toISOString();

    // PostgREST caps a select at 1000 rows and returns no error when it
    // truncates, so an unpaged read would silently report a fraction of the
    // corpus as the whole of it — understating the one number this route
    // exists to state.
    const rows: { verdict: string | null; source_url: string | null; pillar_id: string | null; created_at: string }[] = [];
    for (let from = 0; ; from += 1000) {
      const { data, error } = await supabase
        .from('pillar_evidence')
        .select('verdict, source_url, pillar_id, created_at')
        .gte('created_at', since)
        .range(from, from + 999);
      if (error) throw error;
      rows.push(...(data ?? []));
      if (!data || data.length < 1000) break;
    }

    const documents = new Set(rows.map((r) => r.source_url).filter(Boolean)).size;
    const pillars = new Set(rows.map((r) => r.pillar_id).filter(Boolean)).size;
    const contradictions = rows.filter((r) => /contradict/i.test(r.verdict ?? '')).length;
    const lastFiledISO = rows.length
      ? rows.reduce((m, r) => (r.created_at > m ? r.created_at : m), rows[0].created_at).slice(0, 10)
      : null;

    // The published record. Newest first, contradictions preferred: an intro
    // that leads with "supports" is showing Helm agreeing with the consensus,
    // which is the least interesting thing it does.
    const { data: pub } = await supabase
      .from('content_queue')
      .select('status, content_events!inner(ticker, company, verdict, verbatim_cite, cite_date, run_date, source_type)')
      .eq('status', 'approved');
    const seen = new Set<string>();
    const seenTicker = new Set<string>();
    const recent = ((pub ?? []) as unknown as { content_events: PublishedRow | null }[])
      .map((r) => r.content_events)
      .filter((e): e is PublishedRow => !!e && !!e.verbatim_cite)
      // ONE ENTRY PER TICKER, and one per quote.
      //
      // A list whose job is to prove range reads as the opposite when the same
      // company appears twice, and the published record currently contains 8
      // pairs where one filing was published twice under different sentences
      // (fixed forward in the content cron; the existing rows remain). Keying
      // on the ticker means such a pair can never both surface here, so a data
      // problem in the archive cannot become a credibility problem on the first
      // screen anyone sees.
      .filter((e) => {
        const k = e.verbatim_cite.replace(/\s+/g, ' ').trim().toLowerCase();
        const t = e.ticker.toUpperCase();
        if (seen.has(k) || seenTicker.has(t)) return false;
        seen.add(k);
        seenTicker.add(t);
        return true;
      })
      .sort((a, b) => {
        const av = /contradict/i.test(a.verdict) ? 0 : 1;
        const bv = /contradict/i.test(b.verdict) ? 0 : 1;
        if (av !== bv) return av - bv;
        return String(b.cite_date ?? b.run_date).localeCompare(String(a.cite_date ?? a.run_date));
      })
      .slice(0, 6)
      .map((e) => ({
        ticker: e.ticker,
        company: e.company ?? null,
        verdict: e.verdict,
        verbatimCite: e.verbatim_cite,
        dateISO: String(e.cite_date ?? e.run_date ?? '').slice(0, 10),
        sourceLabel: sourceLabel(e.source_type),
      }));

    const stats: CorpusStats = {
      windowDays: WINDOW_DAYS,
      documents,
      evidence: rows.length,
      contradictions,
      pillars,
      lastFiledISO,
      recent,
    };

    return NextResponse.json(stats, {
      // Changes once a day at most, and every consumer is a marketing surface
      // rather than a decision surface. Long cache, longer stale window.
      headers: { 'Cache-Control': 'public, max-age=1800, stale-while-revalidate=86400' },
    });
  } catch (error) {
    console.error('corpus stats failed:', error instanceof Error ? error.message : 'unknown');
    // A marketing statistic must never be able to break a page that is trying
    // to render. Callers treat null as "say nothing" rather than "say zero" —
    // claiming Helm read zero documents is worse than claiming nothing.
    return NextResponse.json({ error: 'unavailable' }, { status: 503 });
  }
}
