-- Pre-generated AI digest for The Current brief
CREATE TABLE brief_digests (
  id         UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  digest     TEXT NOT NULL,
  holdings   TEXT[] DEFAULT '{}',
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id)  -- one active digest per user, upserted on each generation
);

CREATE INDEX idx_brief_digests_user ON brief_digests(user_id);

ALTER TABLE brief_digests ENABLE ROW LEVEL SECURITY;

-- Users can only read their own digest
CREATE POLICY "Users read own digest"
  ON brief_digests FOR SELECT
  USING (auth.uid() = user_id);

-- Service role writes (cron generates digests)
CREATE POLICY "Service role writes digests"
  ON brief_digests FOR ALL
  USING (true)
  WITH CHECK (true);

COMMENT ON TABLE brief_digests IS 'AI-generated portfolio digest for The Current brief, pre-generated by cron';
